/**
 * Reisedaten der Mein-Schiff-Reise "Norwegens Fjorde".
 *
 * Quelle: Reiseroute / Hafeninformationen aus "Meine Reisen".
 * Die Koordinaten dienen sowohl der Karte als auch der Wetterabfrage.
 *
 * type:
 *   "port" = Liegetag in einem Hafen (mit Ankunfts-/Abfahrtszeit)
 *   "sea"  = Seetag (ungefähre Position auf See, Wetter nur näherungsweise)
 */
const TRIP = {
  title: "Norwegens Fjorde",
  ship: "Mein Schiff 3",
  subtitle: "Mein Schiff 3 · 21. Juni – 1. Juli 2026 · ab Bremerhaven",
  year: 2026,
  // Reihenfolge der Häfen für die Routen-Linie auf der Karte
  days: [
    {
      day: 1,
      date: "2026-06-21",
      weekday: "So",
      type: "port",
      name: "Bremerhaven",
      country: "Deutschland",
      flag: "🇩🇪",
      lat: 53.5396,
      lon: 8.5809,
      portName: "Bremerhaven Cruise Port",
      arrival: "05:30",
      aboard: "16:30",
      departure: "17:00",
      language: "Deutsch",
      currency: "€",
      tz: "GMT+1",
      about:
        "Erleben Sie Bremerhaven von seiner spannendsten Seite und entdecken das Klimahaus, das Schifffahrtsmuseum oder das Deutsche Auswandererhaus.",
    },
    {
      day: 2,
      date: "2026-06-22",
      weekday: "Mo",
      type: "sea",
      name: "Seetag",
      // Ungefähre Position in der Nordsee zwischen Bremerhaven und der norwegischen Küste
      lat: 57.5,
      lon: 6.0,
      approx: true,
      about: "Entdecken Sie unser vielfältiges Programm an Bord.",
    },
    {
      day: 3,
      date: "2026-06-23",
      weekday: "Di",
      type: "port",
      name: "Molde",
      country: "Norwegen",
      flag: "🇳🇴",
      lat: 62.7375,
      lon: 7.1591,
      portName: "Molde",
      arrival: "09:00",
      aboard: null,
      departure: "22:30",
      language: "Norwegisch",
      currency: "nkr",
      tz: "GMT+1",
      about:
        "Vom milden Golfstrom verwöhnt, liegt Molde umgeben von unzähligen Schäreninseln am Nordufer des Moldefjords. Besuchen Sie von hier aus die Atlantik-Küstenstraße, eine der spektakulärsten Küstenstrecken Europas, die teilweise durch das Meer führt. Wenn Ihnen der Sinn nach einem atemberaubenden Ausblick steht, sollten Sie unbedingt vom Hausberg Varden einen Blick auf das beeindruckende Panorama der Sunnmøre-Alpen mit Hunderten zum Teil von Schnee bedeckten Gipfeln werfen. So schön ist Norwegen.",
    },
    {
      day: 4,
      date: "2026-06-24",
      weekday: "Mi",
      type: "port",
      name: "Ålesund",
      country: "Norwegen",
      flag: "🇳🇴",
      lat: 62.4722,
      lon: 6.1549,
      portName: "Ålesund",
      arrival: "07:30",
      aboard: null,
      departure: "22:00",
      language: "Norwegisch",
      currency: "nkr",
      tz: "GMT+1",
      about:
        "Entlang des verzweigten Fjords erstrecken sich die prächtigen, teilweise farbenfroh verzierten Jugendstilbauten von Ålesund. Entdecken Sie das malerische Städtchen und seine maritimen Traditionen bei einem Bummel zu Fuß oder vom Boot aus. Wenn Sie den Überblick behalten möchten, erklimmen Sie auf zauberhaften schmalen Pfaden den Berg Sukkertoppen auf der Insel Hessa. Von hier haben Sie einen einmaligen Blick über den Fjord, die Stadt und die Sunnmørsalpen. Das ist Natur pur.",
    },
    {
      day: 5,
      date: "2026-06-25",
      weekday: "Do",
      type: "port",
      name: "Nordfjordeid",
      country: "Norwegen",
      flag: "🇳🇴",
      lat: 61.9100,
      lon: 5.9920,
      portName: "Nordfjordeid",
      arrival: "08:00",
      aboard: null,
      departure: "20:00",
      language: "Norwegisch",
      currency: "nkr",
      tz: "GMT+1",
      about:
        "Bei der Einfahrt nach Nordfjordeid wird schnell klar, warum der Name des norwegischen Ortes überall Programm ist: Der majestätische Nordfjord ist einfach unübersehbar und unendlich schön. Die Berge, die sich an seinen Ufern auftürmen, sind ein wahres Paradies für Wanderer. Ist Ihnen der Aufstieg zu mühsam, können Sie im Dorf Loen mit der steilsten Seilbahn der Welt bis auf 1.011 Meter fahren. Dort oben erwartet Sie der schönste Blick über Norwegen.",
    },
    {
      day: 6,
      date: "2026-06-26",
      weekday: "Fr",
      type: "port",
      name: "Haugesund",
      country: "Norwegen",
      flag: "🇳🇴",
      lat: 59.4138,
      lon: 5.2680,
      portName: "Haugesund",
      arrival: "09:00",
      aboard: null,
      departure: "19:00",
      language: "Norwegisch",
      currency: "nkr",
      tz: "GMT+1",
      about:
        "Zur Zeit der Heringsfischerei Ende des 19. Jahrhunderts war Haugesund Umschlagpunkt und Poststelle für Seefahrende und Fischer. Heute finden Sie hier eher Stille und Entspannung. Lassen Sie den Blick über die weiten Fjorde schweifen und beobachten Sie das entschleunigte Treiben am Hafen. Sollte Ihnen das zu beschaulich sein, erkunden Sie in den Galerien von Haugesund und Haugeland die imponierenden Grabfunde aus der Wikingerzeit. Auf deren Spuren bietet sich ein Ausflug nach Avaldsnes an, wo sich im Jahr 870 Harald Schönhaar niederließ. Diese und andere kuriose Mythen entdecken Sie im Geschichtszentrum Nordvegen Historiesenter.",
    },
    {
      day: 7,
      date: "2026-06-27",
      weekday: "Sa",
      type: "sea",
      name: "Seetag",
      // Ungefähre Position in der Nordsee auf dem Rückweg nach Bremerhaven
      lat: 56.0,
      lon: 6.5,
      approx: true,
      about: "Entdecken Sie unser vielfältiges Programm an Bord.",
    },
    {
      day: 8,
      date: "2026-06-28",
      weekday: "So",
      type: "port",
      name: "Bremerhaven",
      country: "Deutschland",
      flag: "🇩🇪",
      lat: 53.5396,
      lon: 8.5809,
      portName: "Bremerhaven Cruise Port",
      arrival: "05:30",
      aboard: null,
      departure: "17:00",
      language: "Deutsch",
      currency: "€",
      tz: "GMT+1",
      about:
        "Zwischenstopp in Bremerhaven: Erleben Sie noch einmal das Klimahaus, das Schifffahrtsmuseum oder das Deutsche Auswandererhaus, bevor es zurück Richtung norwegische Fjorde geht.",
    },
    {
      day: 9,
      date: "2026-06-29",
      weekday: "Mo",
      type: "sea",
      name: "Seetag",
      // Ungefähre Position in der Nordsee zwischen Bremerhaven und Bergen
      lat: 57.5,
      lon: 4.5,
      approx: true,
      about: "Entdecken Sie unser vielfältiges Programm an Bord.",
    },
    {
      day: 10,
      date: "2026-06-30",
      weekday: "Di",
      type: "port",
      name: "Bergen",
      country: "Norwegen",
      flag: "🇳🇴",
      lat: 60.3913,
      lon: 5.3221,
      portName: "Bergen",
      arrival: "09:00",
      aboard: null,
      departure: "18:00",
      language: "Norwegisch",
      currency: "nkr",
      tz: "GMT+1",
      // Gebuchter Ausflug laut Reiseplan
      excursion: {
        title: "Besuch der IceBar und Spaziergang durch Bergen",
        time: "14:00 – 17:30",
      },
    },
    {
      day: 11,
      date: "2026-07-01",
      weekday: "Mi",
      type: "port",
      name: "Stavanger",
      country: "Norwegen",
      flag: "🇳🇴",
      lat: 58.9700,
      lon: 5.7331,
      portName: "Stavanger",
      arrival: "08:00",
      aboard: null,
      departure: "19:00",
      language: "Norwegisch",
      currency: "nkr",
      tz: "GMT+1",
    },
  ],
};
